/**
 * Table des pages : sert à la fois au routeur et à la navigation latérale.
 *
 * Les métadonnées — chemin, libellé, icône, groupe — sont statiques, parce que
 * le menu latéral les affiche toutes dès le premier écran. Les vues, elles,
 * sont chargées à la demande : `load` est un import dynamique, que l'outil de
 * construction transforme en un fichier par page. Ouvrir l'accueil ne
 * télécharge donc plus les vingt-trois chapitres du cours de licence ni les
 * cent kilo-octets de récit du mode histoire.
 *
 * Seul l'accueil échappe à la règle : c'est la page servie en premier, et lui
 * imposer un aller-retour de plus au démarrage serait un recul.
 */

import { homeView } from './home.ts';
import type { RouteDefinition } from '../ui/router.ts';

export const NAV_GROUPS: Array<{ id: string; label: string }> = [
  { id: 'accueil', label: 'Accueil' },
  { id: 'apprendre', label: 'Apprendre' },
  { id: 'licence', label: 'Licence radioamateur' },
  { id: 'histoire', label: 'Mode histoire' },
  { id: 'entrainement', label: 'S’entraîner' },
  { id: 'outils', label: 'Outils' },
  { id: 'progression', label: 'Progression' },
  { id: 'reglages', label: 'Réglages' },
];

export const ROUTES: RouteDefinition[] = [
  {
    path: '/',
    label: 'Accueil',
    title: 'Accueil',
    description: 'Point de départ et état de votre progression.',
    icon: '🏠',
    group: 'accueil',
    load: () => Promise.resolve(homeView),
  },
  {
    path: '/apprendre/principes',
    label: 'Comprendre le morse',
    title: 'Comprendre le morse',
    description: "Les règles de durée, la vitesse, Farnsworth et Koch.",
    icon: '📐',
    group: 'apprendre',
    load: () => import('./learn-principles.ts').then((m) => m.principlesView),
  },
  {
    path: '/apprendre/histoire',
    label: 'Histoire',
    title: 'Histoire du morse',
    description: 'De 1794 à aujourd’hui, en dix jalons.',
    icon: '📜',
    group: 'apprendre',
    load: () => import('./learn-history.ts').then((m) => m.historyView),
  },
  {
    path: '/apprendre/alphabet',
    label: 'Alphabet et lexique',
    title: 'Alphabet et lexique',
    description: 'Le code complet, écoutable ligne à ligne.',
    icon: '🔤',
    group: 'apprendre',
    load: () => import('./learn-alphabet.ts').then((m) => m.alphabetView),
  },
  {
    path: '/apprendre/alphabet-otan',
    label: 'Alphabet OTAN',
    title: 'Alphabet OTAN',
    description: 'Épeler à la voix : Alfa, Bravo, Charlie…',
    icon: '🗣️',
    group: 'apprendre',
    load: () => import('./learn-phonetic.ts').then((m) => m.phoneticView),
  },
  {
    path: '/apprendre/communication',
    label: 'Communiquer en morse',
    title: 'Communiquer en morse',
    description: 'Signaux de procédure, codes Q, abréviations et indicatifs.',
    icon: '💬',
    group: 'apprendre',
    load: () => import('./learn-communication.ts').then((m) => m.communicationView),
  },
  {
    path: '/apprendre/radio',
    label: 'Comprendre la radio',
    title: 'Comprendre la radio',
    description: 'Ondes, bandes, propagation et modes d’émission.',
    icon: '📻',
    group: 'apprendre',
    load: () => import('./learn-radio.ts').then((m) => m.radioView),
  },
  {
    path: '/licence',
    label: 'Licence radioamateur',
    title: 'Formation à la licence',
    description: 'Le cours des deux épreuves, ses calculateurs et son questionnaire.',
    icon: '🎓',
    group: 'licence',
    load: () => import('./licence-hub.ts').then((m) => m.licenceHubView),
  },
  {
    path: '/licence/examen',
    label: 'Le certificat d’opérateur',
    title: 'Le certificat d’opérateur',
    description: 'Ce que la licence autorise, et comment se passe l’examen.',
    icon: '🎓',
    group: 'licence',
    menu: false,
    load: () => import('./licence-exam.ts').then((m) => m.licenceExamView),
  },
  {
    path: '/licence/cadre',
    label: 'Le cadre réglementaire',
    title: 'Le cadre réglementaire',
    description: 'Qui décide quoi, du traité mondial à l’arrêté français.',
    icon: '⚖️',
    group: 'licence',
    menu: false,
    load: () => import('./licence-framework.ts').then((m) => m.licenceFrameworkView),
  },
  {
    path: '/licence/emissions',
    label: 'Classes d’émission',
    title: 'Classes d’émission et conditions techniques',
    description: 'Les trois caractères, et ce que la station doit respecter.',
    icon: '📶',
    group: 'licence',
    menu: false,
    load: () => import('./licence-emissions.ts').then((m) => m.licenceEmissionsView),
  },
  {
    path: '/licence/bandes',
    label: 'Bandes et puissances',
    title: 'Fréquences, puissances et statuts',
    description: 'Les vingt-cinq bandes de la région 1, leur statut et leurs limites.',
    icon: '🎚️',
    group: 'licence',
    menu: false,
    load: () => import('./licence-bands.ts').then((m) => m.licenceBandsView),
  },
  {
    path: '/licence/trafic',
    label: 'Le trafic et ses règles',
    title: 'Le trafic et ses règles',
    description: 'S’identifier, écouter, ce qu’on peut dire, et le journal de bord.',
    icon: '📋',
    group: 'licence',
    menu: false,
    load: () => import('./licence-traffic.ts').then((m) => m.licenceTrafficView),
  },
  {
    path: '/licence/station',
    label: 'La station et l’indicatif',
    title: 'La station et l’indicatif',
    description: 'Structure des indicatifs, déclarations, sanctions et trafic à l’étranger.',
    icon: '🪪',
    group: 'licence',
    menu: false,
    load: () => import('./licence-station.ts').then((m) => m.licenceStationView),
  },
  {
    path: '/licence/decibels',
    label: 'Décibels et puissances',
    title: 'Décibels et puissances',
    description: 'Les neuf rapports, les unités de référence, le rendement.',
    icon: '🧮',
    group: 'licence',
    menu: false,
    load: () => import('./licence-decibels.ts').then((m) => m.licenceDecibelsView),
  },
  {
    path: '/licence/antennes',
    label: 'Antennes et lignes',
    title: 'Antennes et lignes de transmission',
    description: 'Dimensionner, calculer une PAR, mesurer des ondes stationnaires.',
    icon: '🗼',
    group: 'licence',
    menu: false,
    load: () => import('./licence-antennas.ts').then((m) => m.licenceAntennasView),
  },
  {
    path: '/licence/securite',
    label: 'Brouillage et sécurité',
    title: 'Brouillage et sécurité',
    description: 'Compatibilité électromagnétique, protection des personnes, foudre.',
    icon: '⚡',
    group: 'licence',
    menu: false,
    load: () => import('./licence-safety.ts').then((m) => m.licenceSafetyView),
  },
  {
    path: '/licence/calcul',
    label: 'Calculer sans se tromper',
    title: 'Calculer sans se tromper',
    description: 'Transformer une équation, manier les multiples, préparer son brouillon.',
    icon: '🔢',
    group: 'licence',
    menu: false,
    load: () => import('./licence-maths.ts').then((m) => m.licenceMathsView),
  },
  {
    path: '/licence/ohm',
    label: 'Lois d’Ohm et de Joule',
    title: 'Lois d’Ohm et de Joule',
    description: 'Quatre grandeurs, douze équations, le code des couleurs et les groupements.',
    icon: '🔌',
    group: 'licence',
    menu: false,
    load: () => import('./licence-ohm.ts').then((m) => m.licenceOhmView),
  },
  {
    path: '/licence/alternatif',
    label: 'Courant alternatif',
    title: 'Courant alternatif, bobines et condensateurs',
    description: 'Valeurs efficaces, réactance, capacitance et constante de temps.',
    icon: '〰️',
    group: 'licence',
    menu: false,
    load: () => import('./licence-ac.ts').then((m) => m.licenceAcView),
  },
  {
    path: '/licence/transformateurs',
    label: 'Transformateurs et mesures',
    title: 'Transformateurs, piles et mesures',
    description: 'Rapport de spires, piles, galvanomètre et instruments de mesure.',
    icon: '🔋',
    group: 'licence',
    menu: false,
    load: () => import('./licence-transformers.ts').then((m) => m.licenceTransformersView),
  },
  {
    path: '/licence/circuits',
    label: 'Filtres et circuits accordés',
    title: 'Filtres et circuits accordés',
    description: 'Fréquence de coupure, loi de Thomson, facteur Q et bande passante.',
    icon: '🎛️',
    group: 'licence',
    menu: false,
    load: () => import('./licence-circuits.ts').then((m) => m.licenceCircuitsView),
  },
  {
    path: '/licence/diodes',
    label: 'Diodes et alimentations',
    title: 'Diodes et alimentations',
    description: 'La jonction PN, les familles de diodes, redresser et stabiliser.',
    icon: '▶️',
    group: 'licence',
    menu: false,
    load: () => import('./licence-diodes.ts').then((m) => m.licenceDiodesView),
  },
  {
    path: '/licence/transistors',
    label: 'Transistors',
    title: 'Transistors',
    description: 'NPN et PNP, le gain, les trois montages, FET et tubes.',
    icon: '🧩',
    group: 'licence',
    menu: false,
    load: () => import('./licence-transistors.ts').then((m) => m.licenceTransistorsView),
  },
  {
    path: '/licence/etages',
    label: 'Amplis et mélangeurs',
    title: 'Amplificateurs, oscillateurs et mélangeurs',
    description: 'Classes d’amplification, oscillateurs, quartz, multiplicateurs et mélange.',
    icon: '📢',
    group: 'licence',
    menu: false,
    load: () => import('./licence-stages.ts').then((m) => m.licenceStagesView),
  },
  {
    path: '/licence/numerique',
    label: 'Ampli op et logique',
    title: 'Amplificateurs opérationnels et circuits logiques',
    description: 'Contre-réaction, portes logiques, binaire et numérisation.',
    icon: '🔣',
    group: 'licence',
    menu: false,
    load: () => import('./licence-digital.ts').then((m) => m.licenceDigitalView),
  },
  {
    path: '/licence/recepteurs',
    label: 'Récepteurs et émetteurs',
    title: 'Récepteurs et émetteurs',
    description: 'Synoptiques, superhétérodyne, fréquence image et échelle S.',
    icon: '📺',
    group: 'licence',
    menu: false,
    load: () => import('./licence-receivers.ts').then((m) => m.licenceReceiversView),
  },
  {
    path: '/licence/modulations',
    label: 'Les modulations',
    title: 'Les modulations',
    description: 'AM, BLU, FM, modes numériques — et la CW pour ce qu’elle est.',
    icon: '🌊',
    group: 'licence',
    menu: false,
    load: () => import('./licence-modulations.ts').then((m) => m.licenceModulationsView),
  },
  {
    path: '/licence/formulaire',
    label: 'Formulaire',
    title: 'Formulaire',
    description: 'Toutes les formules exigibles, filtrables et imprimables.',
    icon: '📄',
    group: 'licence',
    menu: false,
    load: () => import('./licence-formulary.ts').then((m) => m.licenceFormularyView),
  },
  {
    path: '/licence/questionnaire',
    label: 'Questionnaire',
    title: 'Questionnaire de la licence',
    description: 'Examen blanc, séries libres et révision de ses erreurs.',
    icon: '📝',
    group: 'licence',
    menu: false,
    load: () => import('./licence-quiz.ts').then((m) => m.licenceQuizView),
  },
  {
    path: '/histoire',
    label: 'Mode histoire',
    title: 'Mode histoire',
    description: 'Cinq générations de télégraphistes, de 1844 à 1999.',
    icon: '📻',
    group: 'histoire',
    load: () => import('./story.ts').then((m) => m.storyView),
  },
  {
    path: '/entrainement/ecoute',
    label: 'Écoute (Koch)',
    title: 'Entraînement à l’écoute',
    description: 'Reconnaître les caractères au son, méthode Koch.',
    icon: '🎧',
    group: 'entrainement',
    load: () => import('./train-listen.ts').then((m) => m.listenView),
  },
  {
    path: '/entrainement/libre',
    label: 'Série libre',
    title: 'Série libre',
    description: 'Vos caractères, sans limite de durée, avec les statistiques en direct.',
    icon: '🎚️',
    group: 'entrainement',
    load: () => import('./train-free.ts').then((m) => m.freeView),
  },
  {
    path: '/entrainement/emission',
    label: 'Émission',
    title: 'Entraînement à l’émission',
    description: 'Manipulateur droit ou palettes iambiques.',
    icon: '🔑',
    group: 'entrainement',
    load: () => import('./train-send.ts').then((m) => m.sendView),
  },
  {
    path: '/entrainement/mots',
    label: 'Mots et indicatifs',
    title: 'Mots, codes Q et indicatifs',
    description: 'Copier des groupes entiers, pas seulement des caractères.',
    icon: '📡',
    group: 'entrainement',
    load: () => import('./train-words.ts').then((m) => m.wordsView),
  },
  {
    path: '/entrainement/lecture',
    label: 'Lecture visuelle',
    title: 'Lecture visuelle',
    description: 'Réviser sans son, points et traits à l’écran.',
    icon: '👁️',
    group: 'entrainement',
    load: () => import('./train-read.ts').then((m) => m.readView),
  },
  {
    path: '/outils/traducteur',
    label: 'Traducteur',
    title: 'Traducteur texte et morse',
    description: 'Traduire dans les deux sens, écouter, et émettre en lumière.',
    icon: '🔁',
    group: 'outils',
    load: () => import('./translate.ts').then((m) => m.translateView),
  },
  {
    path: '/outils/enregistreur',
    label: 'Enregistreur',
    title: 'Enregistreur d’émission',
    description: 'Capter sa frappe et l’exporter en audio et en texte.',
    icon: '🎙️',
    group: 'outils',
    load: () => import('./record.ts').then((m) => m.recordView),
  },
  {
    path: '/progression/statistiques',
    label: 'Statistiques',
    title: 'Statistiques',
    description: 'Précision par caractère, points faibles, historique.',
    icon: '📊',
    group: 'progression',
    load: () => import('./stats.ts').then((m) => m.statsView),
  },
  {
    path: '/progression/succes',
    label: 'Succès',
    title: 'Succès',
    description: 'Vos paliers, et l’export de votre progression.',
    icon: '🏅',
    group: 'progression',
    load: () => import('./achievements.ts').then((m) => m.achievementsView),
  },
  {
    path: '/reglages',
    label: 'Réglages',
    title: 'Réglages',
    description: 'Vitesse, son, manipulateur, sorties, données.',
    icon: '⚙️',
    group: 'reglages',
    load: () => import('./settings.ts').then((m) => m.settingsView),
  },
];
